name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: compilation 
      run: gcc -Wall -Werror -Wextra -D BUFFER_SIZE=42 -c get_next_line.c -o get_next_line.o

  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
